### Imports

In [1]:
import pandas as pd
import numpy as np

### Read Data

In [2]:
df = pd.read_excel("../../dados/tables/ibge_undergraduate_fields.xlsx")
df.head(10)

,"Tabela 10065 - Pessoas com nível superior completo, por áreas gerais, específicas e detalhadas de formação do curso graduação concluído, segundo o sexo e a cor ou raça",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Variável - Pessoas com pelo menos nível superi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Brasil, Grande Região e Unidade da Federação","Áreas gerais, específicas e detalhadas de form...",Ano x Sexo x Cor ou raça,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Total,NaN,NaN,NaN,NaN,NaN,Homens,NaN,NaN,NaN,NaN,NaN,Mulheres,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Total,Branca,Preta,Amarela,Parda,Indígena,Total,Branca,Preta,Amarela,Parda,Indígena,Total,Branca,Preta,Amarela,Parda,Indígena
5,Brasil,Total,25854291,16118188,1833183,300446,7542900,54107,10478534,6635081,743938,141776,2933180,22134,15375757,9483107,1089245,158670,4609720,31973
6,NaN,01 - Educação,3601124,1923858,316670,17759,1328413,13794,376719,173735,41279,2535,154831,4162,3224405,1750123,275391,15224,1173582,9632
7,NaN,011 - Educação,3564975,1901869,313519,17544,1317843,13570,366686,168211,40133,2486,151599,4081,3198289,1733658,273386,15058,1166244,9489
8,NaN,0111 - Ciência da educação,133309,71369,10857,367,50247,459,14011,6952,1357,46,5547,108,119297,64417,9500,320,44700,350
9,NaN,0112 - Formação de professores de educação inf...,19207,9753,1780,45,7510,119,588,251,91,6,236,5,18619,9502,1689,40,7274,114

In [3]:
# Colocar a linha 5 como colunas
df.columns = df.iloc[4]
df = df.drop(index=range(0, 5))
df.head(10)

4,NaN,NaN,Total,Branca,Preta,Amarela,Parda,Indígena,Total,Branca,Preta,Amarela,Parda,Indígena,Total,Branca,Preta,Amarela,Parda,Indígena
5,Brasil,Total,25854291,16118188,1833183,300446,7542900,54107,10478534,6635081,743938,141776,2933180,22134,15375757,9483107,1089245,158670,4609720,31973
6,NaN,01 - Educação,3601124,1923858,316670,17759,1328413,13794,376719,173735,41279,2535,154831,4162,3224405,1750123,275391,15224,1173582,9632
7,NaN,011 - Educação,3564975,1901869,313519,17544,1317843,13570,366686,168211,40133,2486,151599,4081,3198289,1733658,273386,15058,1166244,9489
8,NaN,0111 - Ciência da educação,133309,71369,10857,367,50247,459,14011,6952,1357,46,5547,108,119297,64417,9500,320,44700,350
9,NaN,0112 - Formação de professores de educação inf...,19207,9753,1780,45,7510,119,588,251,91,6,236,5,18619,9502,1689,40,7274,114
10,NaN,0113 - Formação de professores sem áreas espec...,3108277,1640654,276647,12790,1165759,11881,222975,91867,25896,872,100935,3297,2885302,1548787,250751,11918,1064824,8584
11,NaN,0114 - Formação de professores em áreas especí...,292953,173550,23271,4182,90778,1096,127021,68199,12540,1513,44043,657,165931,105351,10730,2669,46735,440
12,NaN,0115 - Formação de professores de letras,11230,6543,963,160,3549,15,2090,942,248,48,837,14,9139,5600,715,112,2711,1
13,NaN,018 - Programas interdisciplinares e cursos ge...,36149,21989,3151,215,10570,224,10033,5524,1146,49,3232,81,26117,16465,2005,165,7338,143
14,NaN,0188 - Programas interdisciplinares e cursos ...,36149,21989,3151,215,10570,224,10033,5524,1146,49,3232,81,26117,16465,2005,165,7338,143

In [4]:
cols = list(df.columns)
cols[0] = "Local"
cols[1] = "Area"
df.columns = cols

df.head(10)

,Local,Area,Total,Branca,Preta,Amarela,Parda,Indígena,Total,Branca,Preta,Amarela,Parda,Indígena,Total,Branca,Preta,Amarela,Parda,Indígena
5,Brasil,Total,25854291,16118188,1833183,300446,7542900,54107,10478534,6635081,743938,141776,2933180,22134,15375757,9483107,1089245,158670,4609720,31973
6,NaN,01 - Educação,3601124,1923858,316670,17759,1328413,13794,376719,173735,41279,2535,154831,4162,3224405,1750123,275391,15224,1173582,9632
7,NaN,011 - Educação,3564975,1901869,313519,17544,1317843,13570,366686,168211,40133,2486,151599,4081,3198289,1733658,273386,15058,1166244,9489
8,NaN,0111 - Ciência da educação,133309,71369,10857,367,50247,459,14011,6952,1357,46,5547,108,119297,64417,9500,320,44700,350
9,NaN,0112 - Formação de professores de educação inf...,19207,9753,1780,45,7510,119,588,251,91,6,236,5,18619,9502,1689,40,7274,114
10,NaN,0113 - Formação de professores sem áreas espec...,3108277,1640654,276647,12790,1165759,11881,222975,91867,25896,872,100935,3297,2885302,1548787,250751,11918,1064824,8584
11,NaN,0114 - Formação de professores em áreas especí...,292953,173550,23271,4182,90778,1096,127021,68199,12540,1513,44043,657,165931,105351,10730,2669,46735,440
12,NaN,0115 - Formação de professores de letras,11230,6543,963,160,3549,15,2090,942,248,48,837,14,9139,5600,715,112,2711,1
13,NaN,018 - Programas interdisciplinares e cursos ge...,36149,21989,3151,215,10570,224,10033,5524,1146,49,3232,81,26117,16465,2005,165,7338,143
14,NaN,0188 - Programas interdisciplinares e cursos ...,36149,21989,3151,215,10570,224,10033,5524,1146,49,3232,81,26117,16465,2005,165,7338,143

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4588 entries, 5 to 4592
Data columns (total 20 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Local     34 non-null     str
 1   Area      4587 non-null   str
 2   Total     4587 non-null   object
 3   Branca    4587 non-null   object
 4   Preta     4587 non-null   object
 5   Amarela   4587 non-null   object
 6   Parda     4587 non-null   object
 7   Indígena  4587 non-null   object
 8   Total     4587 non-null   object
 9   Branca    4587 non-null   object
 10  Preta     4587 non-null   object
 11  Amarela   4587 non-null   object
 12  Parda     4587 non-null   object
 13  Indígena  4587 non-null   object
 14  Total     4587 non-null   object
 15  Branca    4587 non-null   object
 16  Preta     4587 non-null   object
 17  Amarela   4587 non-null   object
 18  Parda     4587 non-null   object
 19  Indígena  4587 non-null   object
dtypes: object(18), str(2)
memory usage: 717.0+ KB

In [6]:
# 1. Definimos os prefixos para cada intervalo de colunas
prefixos = (
    ["Id"] * 2 +
    ["Pessoas"] * 6 +
    ["Homens"] * 6 +
    ["Mulheres"] * 6
)

# 2. Pegamos os nomes atuais das colunas
nomes_originais = df.columns.astype(str)

# 3. Criamos nomes simples com prefixo
novas_colunas = [
    f"{prefixo}_{nome}".strip()
    for prefixo, nome in zip(prefixos, nomes_originais)
]

# 4. Atribuímos as novas colunas ao dataframe
df.columns = novas_colunas

# 5. Preenche os valores vazios da coluna de localidade
df["Id_Local"] = df["Id_Local"].ffill()

df.head()

,Id_Local,Id_Area,Pessoas_Total,Pessoas_Branca,Pessoas_Preta,Pessoas_Amarela,Pessoas_Parda,Pessoas_Indígena,Homens_Total,Homens_Branca,Homens_Preta,Homens_Amarela,Homens_Parda,Homens_Indígena,Mulheres_Total,Mulheres_Branca,Mulheres_Preta,Mulheres_Amarela,Mulheres_Parda,Mulheres_Indígena
5,Brasil,Total,25854291,16118188,1833183,300446,7542900,54107,10478534,6635081,743938,141776,2933180,22134,15375757,9483107,1089245,158670,4609720,31973
6,Brasil,01 - Educação,3601124,1923858,316670,17759,1328413,13794,376719,173735,41279,2535,154831,4162,3224405,1750123,275391,15224,1173582,9632
7,Brasil,011 - Educação,3564975,1901869,313519,17544,1317843,13570,366686,168211,40133,2486,151599,4081,3198289,1733658,273386,15058,1166244,9489
8,Brasil,0111 - Ciência da educação,133309,71369,10857,367,50247,459,14011,6952,1357,46,5547,108,119297,64417,9500,320,44700,350
9,Brasil,0112 - Formação de professores de educação inf...,19207,9753,1780,45,7510,119,588,251,91,6,236,5,18619,9502,1689,40,7274,114

In [7]:
# mostrar linhas com NaNs e remover ultima linha
df[df.isna().any(axis=1)]

,Id_Local,Id_Area,Pessoas_Total,Pessoas_Branca,Pessoas_Preta,Pessoas_Amarela,Pessoas_Parda,Pessoas_Indígena,Homens_Total,Homens_Branca,Homens_Preta,Homens_Amarela,Homens_Parda,Homens_Indígena,Mulheres_Total,Mulheres_Branca,Mulheres_Preta,Mulheres_Amarela,Mulheres_Parda,Mulheres_Indígena
4592,Fonte: IBGE - Censo Demográfico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df = df.dropna()

In [9]:
def adicionar_hierarquia_area(df, coluna_area=("Id", "Area")):
    df = df.copy()

    extraido = (
        df[coluna_area]
        .astype("string")
        .str.strip()
        .str.extract(r"^(?P<codigo>\d+)\s*-\s*(?P<descricao>.+)$")
    )

    df["codigo_area"] = extraido["codigo"]
    df["descricao_area"] = extraido["descricao"].str.strip()

    # Mapas com os nomes dos grupos e subgrupos
    mapa_grupo = (
        df.loc[df["codigo_area"].str.len().eq(2), ["codigo_area", "descricao_area"]]
        .drop_duplicates()
        .set_index("codigo_area")["descricao_area"]
        .to_dict()
    )

    mapa_subgrupo = (
        df.loc[df["codigo_area"].str.len().eq(3), ["codigo_area", "descricao_area"]]
        .drop_duplicates()
        .set_index("codigo_area")["descricao_area"]
        .to_dict()
    )

    df["codigo_grupo"] = df["codigo_area"].str[:2]
    df["codigo_subgrupo"] = df["codigo_area"].str[:3]

    df["grupo"] = df["codigo_grupo"].map(mapa_grupo)
    df["subgrupo"] = df["codigo_subgrupo"].map(mapa_subgrupo)

    df["nome"] = df["descricao_area"].where(
        df["codigo_area"].str.len().ge(4)
    )

    return df

df = adicionar_hierarquia_area(df, coluna_area=("Id_Area"))

In [10]:
df.head(10)

,Id_Local,Id_Area,Pessoas_Total,Pessoas_Branca,Pessoas_Preta,Pessoas_Amarela,Pessoas_Parda,Pessoas_Indígena,Homens_Total,Homens_Branca,...,Mulheres_Amarela,Mulheres_Parda,Mulheres_Indígena,codigo_area,descricao_area,codigo_grupo,codigo_subgrupo,grupo,subgrupo,nome
5,Brasil,Total,25854291,16118188,1833183,300446,7542900,54107,10478534,6635081,...,158670,4609720,31973,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>
6,Brasil,01 - Educação,3601124,1923858,316670,17759,1328413,13794,376719,173735,...,15224,1173582,9632,01,Educação,01,01,Educação,NaN,<NA>
7,Brasil,011 - Educação,3564975,1901869,313519,17544,1317843,13570,366686,168211,...,15058,1166244,9489,011,Educação,01,011,Educação,Educação,<NA>
8,Brasil,0111 - Ciência da educação,133309,71369,10857,367,50247,459,14011,6952,...,320,44700,350,0111,Ciência da educação,01,011,Educação,Educação,Ciência da educação
9,Brasil,0112 - Formação de professores de educação inf...,19207,9753,1780,45,7510,119,588,251,...,40,7274,114,0112,Formação de professores de educação infantil,01,011,Educação,Educação,Formação de professores de educação infantil
10,Brasil,0113 - Formação de professores sem áreas espec...,3108277,1640654,276647,12790,1165759,11881,222975,91867,...,11918,1064824,8584,0113,Formação de professores sem áreas específicas,01,011,Educação,Educação,Formação de professores sem áreas específicas
11,Brasil,0114 - Formação de professores em áreas especí...,292953,173550,23271,4182,90778,1096,127021,68199,...,2669,46735,440,0114,Formação de professores em áreas específicas (...,01,011,Educação,Educação,Formação de professores em áreas específicas (...
12,Brasil,0115 - Formação de professores de letras,11230,6543,963,160,3549,15,2090,942,...,112,2711,1,0115,Formação de professores de letras,01,011,Educação,Educação,Formação de professores de letras
13,Brasil,018 - Programas interdisciplinares e cursos ge...,36149,21989,3151,215,10570,224,10033,5524,...,165,7338,143,018,Programas interdisciplinares e cursos gerais a...,01,018,Educação,Programas interdisciplinares e cursos gerais a...,<NA>
14,Brasil,0188 - Programas interdisciplinares e cursos ...,36149,21989,3151,215,10570,224,10033,5524,...,165,7338,143,0188,Programas interdisciplinares e cursos gerais ...,01,018,Educação,Programas interdisciplinares e cursos gerais a...,Programas interdisciplinares e cursos gerais ...

In [11]:
# Garantir string, preencher ausentes e normalizar espaços internos
df["nome"] = (
    df["nome"]
    .fillna("Nenhum")
    .astype(str)
    .str.replace(r"\s+", " ", regex=True)  # troca múltiplos espaços por um só
    .str.strip()
)

### Create YAML

In [12]:
# generate a yaml file with the graduation codes and names
  # - graduacao:
  #   - codigo: "01"
  #     descricao: "serviço nas Forças Armadas"

  #   - codigo: "02"
  #     descricao: "serviço policial militar"

with open('../../dados/undergraduate_fields_for_profile.yaml', 'w') as f:
    f.write('  - graduacao:\n')
    for _, row in df.iterrows():
        if row['Id_Local'] != 'Brasil':
            break
        if row['Id_Area'] == 'Total':
            continue
        codigo = (row["Id_Area"].split("-")[0]).strip()
        descricao = "-".join((row["Id_Area"].split("-")[1:])).strip()
        descricao = " ".join(descricao.split())
        if len(codigo) != 4:
            continue
        f.write(f'    - codigo: "{codigo}"\n')
        f.write(f'      descricao: "{descricao}"\n')

In [13]:
# Verificar quais nomes em Id_Area tem mais de um '-'
areas_com_mais_de_um_hifen = df["Id_Area"].apply(lambda x: str(x).count("-") > 1)
nomes_com_mais_de_um_hifen = df.loc[areas_com_mais_de_um_hifen, "Id_Area"].unique()
print("Nomes em Id_Area com mais de um '-':")
for nome in nomes_com_mais_de_um_hifen:
    print(f"- {nome}")

Nomes em Id_Area com mais de um '-':
- 09 - Saúde e bem-estar
- 092 - Bem-estar
- 098 - Programas interdisciplinares e cursos gerais abrangendo saúde e bem-estar
- 0988 - Programas interdisciplinares e cursos gerais abrangendo saúde e bem-estar

In [14]:
# generate a yaml file with the graduation codes and names
# - graduacao:
#   - codigo: "01"
#     descricao: "serviço nas Forças Armadas"

#   - codigo: "02"
#     descricao: "serviço policial militar"

with open('../../dados/undergraduate_fields_for_recommendation.yaml', 'w') as f:
    for _, row in df.iterrows():
        # pular primeira linha, que é o total
        if row['Id_Local'] != 'Brasil':
            break
        if row['Id_Area'] == 'Total':
            continue
        codigo = (row["Id_Area"].split("-")[0]).strip()
        descricao = "-".join((row["Id_Area"].split("-")[1:])).strip()
        descricao = " ".join(descricao.split())
        if len(codigo) != 4:
            continue
        f.write(f'- "{descricao}"\n')